FROM nginx:alpine

# Copy the build directory to the Nginx HTML directory
COPY client/dist/ /usr/share/nginx/html

# Modify the Nginx configuration file to listen on port 5173
RUN echo "server { \
    listen 5173; \
    listen [::]:5173; \
    server_name localhost; \
    location / { \
        root /usr/share/nginx/html; \
        index index.html index.htm; \
    } \
    error_page 500 502 503 504 /50x.html; \
    location = /50x.html { \
        root /usr/share/nginx/html; \
    } \
}" > /etc/nginx/conf.d/default.conf

# Expose port 5173
EXPOSE 5173

# Start Nginx when the container runs
CMD ["nginx", "-g", "daemon off;"]
