# Generated by Django 5.1.3 on 2025-01-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_dataset_evaluationresult_prompt_delete_evaluation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='name',
        ),
    ]
