# Generated by Django 5.1.3 on 2025-01-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_evaluationresult_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationresult',
            name='prompt_text',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
