# Generated by Django 5.1.3 on 2025-01-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0005_evaluationresult_prompt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationresult',
            name='prompt_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
